import fs from 'node:fs';
const DAY=86400000, INITIAL=1000, RISK_PCT=.01;
const SYMBOLS=['BTCUSDT','ETHUSDT','BNBUSDT','XRPUSDT','SOLUSDT'];
function parseLog(s){const txt=fs.readFileSync(`result_${s}.log`,'utf8');const a=txt.indexOf('BACKTEST_RESULT_START'),b=txt.indexOf('BACKTEST_RESULT_END');if(a<0||b<0)throw new Error(`missing result ${s}`);return JSON.parse(txt.slice(a+'BACKTEST_RESULT_START'.length,b).trim())}
function parseCsv(s){const out=[];for(const line of fs.readFileSync(`${s}_5m.csv`,'utf8').trim().split(/\r?\n/)){const x=line.split(',');if(!/^\d+$/.test(x[0]||''))continue;const c={start:+x[0],open:+x[1],high:+x[2],low:+x[3],close:+x[4]};if(Object.values(c).every(Number.isFinite))out.push(c)}return [...new Map(out.map(c=>[c.start,c])).values()].sort((a,b)=>a.start-b.start)}
function recalcDay(t,bars){const dir=t.direction,e=t.entry,sl=t.sl,risk=Math.abs(e-sl),tp2=dir==='LONG'?e+3*risk:e-3*risk,fi=bars.findIndex(c=>c.start===t.fill);if(fi<0)return null;const endT=t.fill+DAY;for(let i=fi+1;i<bars.length&&bars[i].start<=endT;i++){const c=bars[i],sh=dir==='LONG'?c.low<=sl:c.high>=sl,th=dir==='LONG'?c.high>=tp2:c.low<=tp2;if(sh&&th)return {...t,r:-1,exit:c.start,exit_reason:'AMBIGUOUS_SL_FIRST',hold_days:(c.start-t.fill)/DAY};if(th)return {...t,r:3,exit:c.start,exit_reason:'TP3R',hold_days:(c.start-t.fill)/DAY};if(sh)return {...t,r:-1,exit:c.start,exit_reason:'SL',hold_days:(c.start-t.fill)/DAY}}
 const end=bars.find(c=>c.start>=endT)||bars.at(-1);const rr=(dir==='LONG'?(end.close-e):(e-end.close))/risk;return {...t,r:rr,exit:end.start,exit_reason:'TIME_24H',hold_days:(end.start-t.fill)/DAY};}
function dedupe(xs){const m=new Map();for(const x of xs){const k=`${x.symbol}:${x.type}:${x.signal}:${x.direction}:${Number(x.entry).toFixed(8)}:${Number(x.sl).toFixed(8)}`;if(!m.has(k))m.set(k,x)}return [...m.values()]}
function stats(xs){const a=xs.filter(x=>Number.isFinite(x.r)).sort((x,y)=>x.fill-y.fill);let eq=INITIAL,peak=eq,mdd=0,ls=0,maxls=0;for(const t of a){eq+=eq*RISK_PCT*t.r;peak=Math.max(peak,eq);mdd=Math.max(mdd,(peak-eq)/peak);if(t.r<=0){ls++;maxls=Math.max(maxls,ls)}else ls=0}const wins=a.filter(x=>x.r>0).length;return{trades:a.length,wins,losses:a.length-wins,win_rate:a.length?wins/a.length:null,avg_r:a.length?a.reduce((s,x)=>s+x.r,0)/a.length:null,final_equity:eq,return_pct:(eq/INITIAL-1)*100,max_drawdown_pct:mdd*100,max_consecutive_losses:maxls,avg_hold_days:a.length?a.reduce((s,x)=>s+(x.hold_days||0),0)/a.length:null}}
const all=[];const per_symbol={};
for(const s of SYMBOLS){const j=parseLog(s),bars=parseCsv(s);const day=dedupe((j.day_trades||[]).map(x=>({...x,symbol:s}))).map(x=>recalcDay(x,bars)).filter(Boolean);const swing=dedupe((j.swing_trades||[]).map(x=>({...x,symbol:s})));const combo=[...day,...swing];per_symbol[s]={DAY:stats(day),SWING:stats(swing),COMBINED:stats(combo)};all.push(...combo)}
const unique=dedupe(all),dayAll=unique.filter(x=>x.type==='DAY'),swingAll=unique.filter(x=>x.type==='SWING');const activeDays=new Set(dayAll.map(x=>new Date(x.fill).toISOString().slice(0,10)));const start=Date.parse('2026-01-01T00:00:00Z'),end=Math.max(...unique.map(x=>x.fill),Date.now()),elapsedDays=Math.floor((end-start)/DAY)+1;const byMonth={};for(const x of unique){const m=new Date(x.fill).toISOString().slice(0,7);byMonth[m]??={DAY:0,SWING:0,TOTAL:0};byMonth[m][x.type]++;byMonth[m].TOTAL++}
console.log('TOP5_RESULT_START');console.log(JSON.stringify({universe:SYMBOLS,initial_equity:INITIAL,risk_per_trade_pct:RISK_PCT,day_max_hold:'24h',swing_max_hold:'14d',per_symbol,portfolio:{DAY:stats(dayAll),SWING:stats(swingAll),COMBINED:stats(unique),active_day_count:activeDays.size,elapsed_calendar_days:elapsedDays,day_signal_coverage_pct:activeDays.size/elapsedDays*100,avg_entries_per_calendar_day:unique.length/elapsedDays},by_month:byMonth},null,2));console.log('TOP5_RESULT_END');