import fs from 'node:fs';
const DAY=86400000, INITIAL=1000, LEVERAGE=10, TRADE_RISK_PCT=.03, TOTAL_RISK_CAP=.06, MAX_POS=2;
const SYMBOLS=['BTCUSDT','ETHUSDT','BNBUSDT'];
const START=Date.parse('2025-01-01T00:00:00Z'), END=Date.parse('2025-12-31T23:59:59Z');
function parseLog(s){const txt=fs.readFileSync(`result_${s}.log`,'utf8');const a=txt.indexOf('BACKTEST_RESULT_START'),b=txt.indexOf('BACKTEST_RESULT_END');return JSON.parse(txt.slice(a+'BACKTEST_RESULT_START'.length,b).trim());}
function parseCsv(s){const out=[];for(const line of fs.readFileSync(`${s}_5m.csv`,'utf8').trim().split(/\r?\n/)){const x=line.split(',');if(!/^\d+$/.test(x[0]||''))continue;const c={start:+x[0],open:+x[1],high:+x[2],low:+x[3],close:+x[4]};if(Object.values(c).every(Number.isFinite))out.push(c)}return [...new Map(out.map(c=>[c.start,c])).values()].sort((a,b)=>a.start-b.start)}
function recalcDay(t,bars){const dir=t.direction,e=t.entry,sl=t.sl,risk=Math.abs(e-sl),tp=dir==='LONG'?e+3*risk:e-3*risk;const fi=bars.findIndex(c=>c.start===t.fill);if(fi<0||!(risk>0)||!(e>0))return null;if((dir==='LONG'&&!(sl<e))||(dir==='SHORT'&&!(sl>e)))return null;const done=(r,exit,reason,px)=>({...t,r,exit,exit_reason:reason,hold_days:(exit-t.fill)/DAY,exit_price:px,price_return:dir==='LONG'?(px-e)/e:(e-px)/e,stop_pct:risk/e});const endT=Math.min(t.fill+3*DAY,END);for(let i=fi+1;i<bars.length&&bars[i].start<=endT;i++){const c=bars[i],sh=dir==='LONG'?c.low<=sl:c.high>=sl,th=dir==='LONG'?c.high>=tp:c.low<=tp;if(sh&&th)return done(-1,c.start,'AMBIGUOUS_SL_FIRST',sl);if(th)return done(3,c.start,'TP3R',tp);if(sh)return done(-1,c.start,'SL',sl)}const end=bars.find(c=>c.start>=endT)||bars.filter(c=>c.start<=END).at(-1);if(!end)return null;const rr=(dir==='LONG'?(end.close-e):(e-end.close))/risk;return done(rr,end.start,'TIME_72H',end.close)}
function dedupe(xs){const m=new Map();for(const x of xs){const k=`${x.symbol}:${x.type}:${x.signal}:${x.direction}:${x.fill}:${Number(x.entry).toFixed(8)}:${Number(x.sl).toFixed(8)}`;if(!m.has(k))m.set(k,x)}return [...m.values()]}
const candidates=[];for(const s of SYMBOLS){const j=parseLog(s),bars=parseCsv(s);const day=dedupe((j.day_trades||[]).map(x=>({...x,symbol:s}))).filter(x=>x.fill>=START&&x.fill<=END).map(x=>recalcDay(x,bars)).filter(Boolean);candidates.push(...day)}candidates.sort((a,b)=>a.fill-b.fill||a.symbol.localeCompare(b.symbol));
let equity=INITIAL,peak=INITIAL,mdd=0,maxConcurrent=0,blockedRisk=0,blockedSlots=0,blockedMargin=0;const open=[],accepted=[];let maxOpenRiskPct=0,maxUsedMarginPct=0;
function settleUntil(ts){while(true){let idx=-1,min=Infinity;for(let i=0;i<open.length;i++)if(open[i].exit<=ts&&open[i].exit<min){min=open[i].exit;idx=i}if(idx<0)break;const p=open.splice(idx,1)[0];equity+=p.pnl;peak=Math.max(peak,equity);mdd=Math.max(mdd,(peak-equity)/peak)}}
for(const t of candidates){settleUntil(t.fill);if(equity<=0)break;if(open.length>=MAX_POS){blockedSlots++;continue}const openRisk=open.reduce((s,p)=>s+p.risk_dollars,0),usedMargin=open.reduce((s,p)=>s+p.margin,0);const intendedRisk=equity*TRADE_RISK_PCT;const desiredNotional=intendedRisk/t.stop_pct;const availableMargin=Math.max(0,equity-usedMargin);const notional=Math.min(desiredNotional,availableMargin*LEVERAGE);const margin=notional/LEVERAGE,riskDollars=notional*t.stop_pct;if(!(notional>0)||riskDollars<=0){blockedMargin++;continue}if(openRisk+riskDollars>equity*TOTAL_RISK_CAP+1e-9){blockedRisk++;continue}const pnl=notional*t.price_return;const p={...t,equity_before:equity,notional,margin,risk_dollars:riskDollars,risk_pct_equity:riskDollars/equity*100,pnl};open.push(p);accepted.push(p);maxConcurrent=Math.max(maxConcurrent,open.length);maxOpenRiskPct=Math.max(maxOpenRiskPct,open.reduce((s,p)=>s+p.risk_dollars,0)/equity*100);maxUsedMarginPct=Math.max(maxUsedMarginPct,open.reduce((s,p)=>s+p.margin,0)/equity*100)}settleUntil(Infinity);
let streak=0,maxLosingStreak=0;for(const p of accepted){if(p.pnl<=0){streak++;maxLosingStreak=Math.max(maxLosingStreak,streak)}else streak=0}
const wins=accepted.filter(x=>x.pnl>0),losses=accepted.filter(x=>x.pnl<=0);const sum=a=>a.reduce((s,x)=>s+x,0), avg=a=>a.length?sum(a)/a.length:null;const bySymbol={};for(const s of SYMBOLS){const a=accepted.filter(x=>x.symbol===s),w=a.filter(x=>x.pnl>0);bySymbol[s]={trades:a.length,wins:w.length,losses:a.length-w.length,win_rate:a.length?w.length/a.length*100:null,pnl:sum(a.map(x=>x.pnl)),avg_r:avg(a.map(x=>x.r)),avg_hold_hours:avg(a.map(x=>x.hold_days*24))}}
const result={period:[new Date(START).toISOString(),new Date(END).toISOString()],max_hold_hours:72,candidates:candidates.length,trades:accepted.length,wins:wins.length,losses:losses.length,win_rate:accepted.length?wins.length/accepted.length*100:null,avg_r:avg(accepted.map(x=>x.r)),avg_hold_hours:avg(accepted.map(x=>x.hold_days*24)),median_hold_hours:accepted.length?[...accepted].sort((a,b)=>a.hold_days-b.hold_days)[Math.floor(accepted.length/2)].hold_days*24:null,time_exit_count:accepted.filter(x=>x.exit_reason==='TIME_72H').length,final_equity:equity,net_pnl:equity-INITIAL,return_pct:(equity/INITIAL-1)*100,mdd_pct:mdd*100,max_losing_streak:maxLosingStreak,max_concurrent:maxConcurrent,max_open_risk_pct:maxOpenRiskPct,max_used_margin_pct:maxUsedMarginPct,blockedRisk,blockedSlots,blockedMargin,avg_margin:avg(accepted.map(x=>x.margin)),avg_notional:avg(accepted.map(x=>x.notional)),avg_risk_dollars:avg(accepted.map(x=>x.risk_dollars)),avg_risk_pct:avg(accepted.map(x=>x.risk_pct_equity)),gross_profit:sum(wins.map(x=>x.pnl)),gross_loss:sum(losses.map(x=>x.pnl)),max_win:accepted.length?Math.max(...accepted.map(x=>x.pnl)):null,max_loss:accepted.length?Math.min(...accepted.map(x=>x.pnl)):null,bySymbol};
console.log('PORTFOLIO_RESULT_START');console.log(JSON.stringify(result,null,2));console.log('PORTFOLIO_RESULT_END');fs.writeFileSync('portfolio_2025_risk3_max2_3d.json',JSON.stringify(result,null,2));fs.writeFileSync('trades_2025_risk3_max2_3d.json',JSON.stringify(accepted,null,2));