import fs from 'node:fs';
import { evaluateEntryTrigger } from './entry_trigger.js';

const SYMBOL='BTCUSDT', DAY=86400000, TFMS={'5':300000,'15':900000,'60':3600000};
function parseVision5(path='btc5m.csv'){
  const rows=fs.readFileSync(path,'utf8').trim().split(/\r?\n/), out=[];
  for(const line of rows){const x=line.split(','); if(!/^\d+$/.test(x[0]||'')) continue; const c={start:+x[0],open:+x[1],high:+x[2],low:+x[3],close:+x[4]}; if(Object.values(c).every(Number.isFinite))out.push(c)}
  const m=new Map(out.map(c=>[c.start,c])); return [...m.values()].sort((a,b)=>a.start-b.start)
}
function aggregate(cs,minutes){const ms=minutes*60000,m=new Map();for(const c of cs){const k=Math.floor(c.start/ms)*ms;let a=m.get(k);if(!a){a={start:k,open:c.open,high:c.high,low:c.low,close:c.close};m.set(k,a)}else{a.high=Math.max(a.high,c.high);a.low=Math.min(a.low,c.low);a.close=c.close}}return[...m.values()].sort((a,b)=>a.start-b.start)}
function range(c){return Math.max(c.high-c.low,1e-12)} function body(c){return Math.abs(c.close-c.open)}
function htfDisplacement(cs,i,direction){if(i<5||i>=cs.length)return false;const c=cs[i],prior=cs.slice(i-5,i),ar=prior.reduce((a,x)=>a+range(x),0)/prior.length,ab=prior.reduce((a,x)=>a+body(x),0)/prior.length,r=range(c);const directional=direction==='LONG'?c.close>c.open:c.close<c.open;const loc=direction==='LONG'?(c.close-c.low)/r:(c.high-c.close)/r;return directional&&r>=Math.max(ar*1.25,1e-12)&&body(c)>=Math.max(ab*1.35,r*0.5)&&loc>=0.65}
function latestDirectionalFvgClosed(cs,direction,tf){for(let i=cs.length-1;i>=2;i--){const a=cs[i-2],c=cs[i];let low=null,high=null,kind=null;if(direction==='LONG'&&c.low>a.high){low=a.high;high=c.low;kind='BULL_FVG'}if(direction==='SHORT'&&c.high<a.low){low=c.high;high=a.low;kind='BEAR_FVG'}if(low===null)continue;if(!htfDisplacement(cs,i-1,direction))continue;const later=cs.slice(i+1),invalid=later.some(x=>direction==='LONG'?x.close<low:x.close>high);if(invalid)continue;return{symbol:SYMBOL,direction,score:null,poi_low:low,poi_high:high,poi_tf:tf,poi_source:kind,poi_created_at:c.start,minimum_rr:1.5}}return null}
function poiId(p){return `${p.direction}:${p.poi_tf}:${p.poi_low}:${p.poi_high}:${p.poi_created_at}`}
function closedThrough(cs,t,tf){const ms=TFMS[tf];return cs.filter(c=>c.start+ms<=t)} function touchesMid(c,mid){return c.low<=mid&&c.high>=mid}
function outcome(sig,all5,startIdx){const t=sig.trigger,dir=t.direction,entry=t.entry_mid,sl=t.structural_sl,tp1=t.tp1,tp2=t.tp2;let fillIndex=null,fill=null;for(let i=startIdx;i<all5.length;i++){const c=all5[i],invalid=dir==='LONG'?c.low<=sl:c.high>=sl;if(touchesMid(c,entry)){fillIndex=i;fill=c.start;break}if(invalid)return{filled:false,reason:'invalid_before_mid'}}if(fillIndex===null)return{filled:false,reason:'never_mid'};let hit1=false,hit2=false,loss=false,exit1=null,exit2=null,slAt=null;for(let i=fillIndex;i<all5.length;i++){const c=all5[i],slHit=dir==='LONG'?c.low<=sl:c.high>=sl,t1=dir==='LONG'?c.high>=tp1:c.low<=tp1,t2=dir==='LONG'?c.high>=tp2:c.low<=tp2;if(slHit&&i===fillIndex){loss=true;slAt=c.start;break}if(!hit1&&t1){hit1=true;exit1=c.start}if(!hit2&&t2){hit2=true;exit2=c.start;break}if(slHit){loss=true;slAt=c.start;break}}return{filled:true,fill,hit1,hit2,loss,exit1,exit2,slAt,open:!hit2&&!loss}}

const all5=parseVision5(), m15=aggregate(all5,15), h1=aggregate(all5,60);const end=Math.floor((Date.now()-TFMS['5'])/TFMS['5'])*TFMS['5'],start=end-30*DAY;const eval5=all5.filter(c=>c.start>=start&&c.start<=end),indexByStart=new Map(all5.map((c,i)=>[c.start,i])),consumed=new Set(),cycles=new Set(),signals=[];
console.log(JSON.stringify({phase:'loaded',source:'Binance Vision USD-M futures BTCUSDT',period:{start:new Date(start).toISOString(),end:new Date(end).toISOString()},bars:{m5:all5.length,m15:m15.length,h1:h1.length}}));
for(const c of eval5){const t=c.start+TFMS['5'],hist5=closedThrough(all5,t,'5').slice(-120),c15=closedThrough(m15,t,'15').slice(-100),c60=closedThrough(h1,t,'60').slice(-100);for(const dir of ['LONG','SHORT'])for(const [cs,tf] of [[c15,'15m'],[c60,'1H']]){const p=latestDirectionalFvgClosed(cs,dir,tf);if(!p)continue;const pid=poiId(p);if(consumed.has(pid))continue;const e=evaluateEntryTrigger({candles5m:hist5,item:p});if(!e.ready||!e.trigger)continue;const tr=e.trigger;if(tr.retrace_start!==hist5.at(-1)?.start||cycles.has(tr.cycle_id))continue;cycles.add(tr.cycle_id);consumed.add(pid);const o=outcome({trigger:tr},all5,indexByStart.get(c.start));signals.push({signal_start:c.start,signal_iso:new Date(c.start).toISOString(),direction:dir,poi_tf:tf,poi_low:p.poi_low,poi_high:p.poi_high,poi_created_at:p.poi_created_at,entry:tr.entry_mid,sl:tr.structural_sl,tp1:tr.tp1,tp2:tr.tp2,live_rr:tr.live_rr,...o})}}
const filled=signals.filter(x=>x.filled),resolved=filled.filter(x=>!x.open),wins1=resolved.filter(x=>x.hit1).length,wins2=resolved.filter(x=>x.hit2).length,losses=resolved.filter(x=>x.loss).length,rrs=signals.map(x=>x.live_rr).filter(Number.isFinite).sort((a,b)=>a-b);const byTf=Object.fromEntries(['15m','1H'].map(tf=>{const a=signals.filter(x=>x.poi_tf===tf),f=a.filter(x=>x.filled),r=f.filter(x=>!x.open);return[tf,{signals:a.length,filled:f.length,resolved:r.length,tp1_hits:r.filter(x=>x.hit1).length,tp2_hits:r.filter(x=>x.hit2).length,losses:r.filter(x=>x.loss).length}]}));const byDir=Object.fromEntries(['LONG','SHORT'].map(d=>{const a=signals.filter(x=>x.direction===d),f=a.filter(x=>x.filled),r=f.filter(x=>!x.open);return[d,{signals:a.length,filled:f.length,resolved:r.length,tp1_hits:r.filter(x=>x.hit1).length,tp2_hits:r.filter(x=>x.hit2).length,losses:r.filter(x=>x.loss).length}]}));
const summary={symbol:SYMBOL,data_source:'Binance Vision USD-M futures (proxy because Bybit blocked GitHub runner with HTTP 403)',model:'final dynamic 1H/15m POI -> 5m sweep/MSS+displacement/strict-FVG first retrace, min live RR 1.5',period:{start:new Date(start).toISOString(),end:new Date(end).toISOString(),days:30},entry_signals:signals.length,mid_filled:filled.length,unfilled:signals.length-filled.length,resolved:resolved.length,open:filled.filter(x=>x.open).length,sl_losses:losses,tp1_hits:wins1,tp2_hits:wins2,tp1_win_rate_resolved:resolved.length?wins1/resolved.length:null,tp2_win_rate_resolved:resolved.length?wins2/resolved.length:null,avg_live_rr:rrs.length?rrs.reduce((a,b)=>a+b,0)/rrs.length:null,median_live_rr:rrs.length?rrs[Math.floor(rrs.length/2)]:null,expectancy_all_out_2R:resolved.length?(wins1*2-(resolved.length-wins1))/resolved.length:null,expectancy_all_out_3R:resolved.length?(wins2*3-(resolved.length-wins2))/resolved.length:null,by_tf:byTf,by_direction:byDir};console.log('BACKTEST_RESULT_START');console.log(JSON.stringify({summary,signals},null,2));console.log('BACKTEST_RESULT_END');
