import fs from 'node:fs';
import { evaluateEntryTrigger } from './entry_trigger.js';

const SYMBOL='BTCUSDT', DAY=86400000, H=3600000, INITIAL=1000, RISK=0.01;
const START=Date.parse('2026-01-01T00:00:00Z');
const END=Math.floor((Date.now()-300000)/300000)*300000;
const MAX_SWING=14*DAY;

function parse(path='btc5m.csv'){
  const out=[];
  for(const line of fs.readFileSync(path,'utf8').trim().split(/\r?\n/)){
    const x=line.split(','); if(!/^\d+$/.test(x[0]||'')) continue;
    const c={start:+x[0],open:+x[1],high:+x[2],low:+x[3],close:+x[4]};
    if(Object.values(c).every(Number.isFinite)) out.push(c);
  }
  return [...new Map(out.map(c=>[c.start,c])).values()].sort((a,b)=>a.start-b.start);
}
function agg(cs,min){const ms=min*60000,m=new Map();for(const c of cs){const k=Math.floor(c.start/ms)*ms;let a=m.get(k);if(!a){a={start:k,open:c.open,high:c.high,low:c.low,close:c.close};m.set(k,a)}else{a.high=Math.max(a.high,c.high);a.low=Math.min(a.low,c.low);a.close=c.close}}return [...m.values()].sort((a,b)=>a.start-b.start)}
function range(c){return Math.max(c.high-c.low,1e-12)} function body(c){return Math.abs(c.close-c.open)}
function avg(xs){return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0}
function atr(cs,n=14){return avg(cs.slice(-n).map(range))||0}
function disp(cs,i,dir,mr=1.25,mb=1.35){if(i<5||i>=cs.length)return false;const c=cs[i],p=cs.slice(i-5,i),r=range(c),ar=avg(p.map(range)),ab=avg(p.map(body)),d=dir==='LONG'?c.close>c.open:c.close<c.open,loc=dir==='LONG'?(c.close-c.low)/r:(c.high-c.close)/r;return d&&r>=ar*mr&&body(c)>=Math.max(ab*mb,r*.5)&&loc>=.65}
function piv(cs,l=2,r=2){const highs=[],lows=[];for(let i=l;i<cs.length-r;i++){let ph=true,pl=true;for(let j=i-l;j<=i+r;j++)if(j!==i){if(cs[j].high>=cs[i].high)ph=false;if(cs[j].low<=cs[i].low)pl=false}if(ph)highs.push({i,price:cs[i].high,start:cs[i].start});if(pl)lows.push({i,price:cs[i].low,start:cs[i].start})}return{highs,lows}}
function overlap(c,lo,hi){return c.high>=Math.min(lo,hi)&&c.low<=Math.max(lo,hi)}
function closed(cs,t,ms){return cs.filter(c=>c.start+ms<=t)}
function activeFvg(cs,dir,tf){for(let i=cs.length-1;i>=2;i--){const a=cs[i-2],c=cs[i];let lo,hi;if(dir==='LONG'&&c.low>a.high){lo=a.high;hi=c.low}else if(dir==='SHORT'&&c.high<a.low){lo=c.high;hi=a.low}else continue;if(!disp(cs,i-1,dir))continue;const later=cs.slice(i+1),bad=later.some(x=>dir==='LONG'?x.close<lo:x.close>hi);if(!bad)return{symbol:SYMBOL,direction:dir,poi_low:lo,poi_high:hi,poi_tf:tf,poi_source:`${tf}_FVG`,poi_created_at:c.start,minimum_rr:1.5}}return null}
function levelPoi(level,dir,tf,source,created,width){if(!Number.isFinite(level)||!Number.isFinite(width)||width<=0)return null;return{symbol:SYMBOL,direction:dir,poi_low:level-width,poi_high:level+width,poi_tf:tf,poi_source:source,poi_created_at:created,minimum_rr:1.5}}
function previousDayLevels(D,t,width){const prev=D.filter(c=>c.start+DAY<=t).at(-1);if(!prev)return[];return[levelPoi(prev.low,'LONG','1D','PDL',prev.start,width),levelPoi(prev.high,'SHORT','1D','PDH',prev.start,width)].filter(Boolean)}
function asianLevels(all5,t,width){const now=new Date(t),dayStart=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate());const asiaStart=dayStart,asiaEnd=dayStart+8*H;if(t<asiaEnd)return[];const bars=all5.filter(c=>c.start>=asiaStart&&c.start<asiaEnd);if(!bars.length)return[];const hi=Math.max(...bars.map(c=>c.high)),lo=Math.min(...bars.map(c=>c.low));return[levelPoi(lo,'LONG','ASIA','ASIA_LOW',asiaEnd,width),levelPoi(hi,'SHORT','ASIA','ASIA_HIGH',asiaEnd,width)].filter(Boolean)}
function swingLiquidityPois(cs,tf,width,lookback=80,maxEach=2){const x=cs.slice(-lookback),p=piv(x),out=[];for(const q of p.lows.slice(-maxEach))out.push(levelPoi(q.price,'LONG',tf,`${tf}_SWING_LOW`,q.start,width));for(const q of p.highs.slice(-maxEach))out.push(levelPoi(q.price,'SHORT',tf,`${tf}_SWING_HIGH`,q.start,width));return out.filter(Boolean)}
function dayPois({a15,a60,a240,D,all5,t}){const ref=a15.at(-1)?.close||a60.at(-1)?.close||0,w=Math.max(atr(a15,14)*.08,ref*.00035);const out=[];for(const dir of ['LONG','SHORT']){const f15=activeFvg(a15,dir,'15m');if(f15)out.push(f15);const f60=activeFvg(a60,dir,'1H');if(f60)out.push(f60)}out.push(...previousDayLevels(D,t,w),...asianLevels(all5,t,w),...swingLiquidityPois(a60,'1H',w,80,2),...swingLiquidityPois(a240,'4H',w*1.25,80,1));const seen=new Set();return out.filter(p=>{const k=`${p.direction}:${p.poi_source}:${p.poi_created_at}:${p.poi_low.toFixed(2)}:${p.poi_high.toFixed(2)}`;if(seen.has(k))return false;seen.add(k);return true})}
function dayOutcome(tr,all5,startIdx){const dir=tr.direction,e=tr.entry_mid,sl=tr.structural_sl,t1=tr.tp1,t2=tr.tp2,expire=startIdx+6;let fi=null;for(let i=startIdx;i<all5.length&&i<=expire;i++){const c=all5[i],bad=dir==='LONG'?c.low<=sl:c.high>=sl;if(c.low<=e&&c.high>=e){if(bad)return{filled:false,reason:'ambiguous_fill_sl'};fi=i;break}if(bad)return{filled:false,reason:'invalid_before_fill'}}if(fi===null)return{filled:false,reason:'expired'};let h1=false,h2=false,loss=false,exit=null;for(let i=fi+1;i<all5.length;i++){const c=all5[i],sh=dir==='LONG'?c.low<=sl:c.high>=sl,a=dir==='LONG'?c.high>=t1:c.low<=t1,b=dir==='LONG'?c.high>=t2:c.low<=t2;if(sh&&b){loss=true;exit=c.start;break}if(!h1&&a)h1=true;if(b){h2=true;exit=c.start;break}if(sh){loss=true;exit=c.start;break}}return{filled:true,fill:all5[fi].start,hit1:h1,hit2:h2,loss,exit,open:!h2&&!loss}}
function swingSetup(h4,h1,dir,poi){if(h4.length<20||h1.length<30)return null;let arr=-1;for(let i=Math.max(1,h4.length-30);i<h4.length;i++)if(overlap(h4[i],poi.poi_low,poi.poi_high)&&!overlap(h4[i-1],poi.poi_low,poi.poi_high))arr=i;if(arr<0)return null;const pv4=piv(h4);let sw=null;if(dir==='LONG'){for(const p of pv4.lows.filter(x=>x.i<arr).reverse()){for(let i=arr;i<h4.length;i++)if(h4[i].low<p.price&&h4[i].close>p.price){sw={i,start:h4[i].start,level:p.price,extreme:h4[i].low};break}if(sw)break}}else{for(const p of pv4.highs.filter(x=>x.i<arr).reverse()){for(let i=arr;i<h4.length;i++)if(h4[i].high>p.price&&h4[i].close<p.price){sw={i,start:h4[i].start,level:p.price,extreme:h4[i].high};break}if(sw)break}}if(!sw)return null;const hs=h1.filter(c=>c.start>=sw.start);if(hs.length<6)return null;const pre=h1.filter(c=>c.start<sw.start).slice(-24),pv1=piv(pre),opp=dir==='LONG'?pv1.highs.at(-1):pv1.lows.at(-1);if(!opp)return null;let mi=-1;for(let i=0;i<hs.length;i++){const broke=dir==='LONG'?hs[i].close>opp.price:hs[i].close<opp.price;if(broke&&disp(hs,i,dir,1.2,1.25)){mi=i;break}}if(mi<0)return null;for(let i=Math.max(2,mi);i<hs.length;i++){const a=hs[i-2],c=hs[i];let lo,hi;if(dir==='LONG'&&c.low>a.high){lo=a.high;hi=c.low}else if(dir==='SHORT'&&c.high<a.low){lo=c.high;hi=a.low}else continue;let first=-1;for(let j=i+1;j<hs.length;j++)if(overlap(hs[j],lo,hi)){first=j;break}if(first!==hs.length-1)continue;const e=(lo+hi)/2,sl=sw.extreme;if(dir==='LONG'&&sl>=e||dir==='SHORT'&&sl<=e)continue;const risk=Math.abs(e-sl);return{direction:dir,entry:e,sl,risk,signal:hs[first].start,poi_tf:poi.poi_tf,poi_low:poi.poi_low,poi_high:poi.poi_high,sweep:sw.start,mss:hs[mi].start}}return null}
function swingTarget(s,h4,d1){const pv=[...piv(d1).highs.map(x=>({...x,tf:'1D'})),...piv(h4).highs.map(x=>({...x,tf:'4H'}))],pl=[...piv(d1).lows.map(x=>({...x,tf:'1D'})),...piv(h4).lows.map(x=>({...x,tf:'4H'}))];const pool=(s.direction==='LONG'?pv:pl).filter(x=>s.direction==='LONG'?x.price>s.entry:x.price<s.entry).sort((a,b)=>Math.abs(a.price-s.entry)-Math.abs(b.price-s.entry));return pool[0]||null}
function swingOutcome(s,all5,startIdx,target){const e=s.entry,sl=s.sl,dir=s.direction,tp=target.price,expirySignal=s.signal+24*H;let fi=null;for(let i=startIdx;i<all5.length&&all5[i].start<=expirySignal;i++){const c=all5[i],bad=dir==='LONG'?c.low<=sl:c.high>=sl;if(c.low<=e&&c.high>=e){if(bad)return{filled:false,reason:'ambiguous_fill_sl'};fi=i;break}if(bad)return{filled:false,reason:'invalid_before_fill'}}if(fi===null)return{filled:false,reason:'expired'};const maxT=all5[fi].start+MAX_SWING;for(let i=fi+1;i<all5.length&&all5[i].start<=maxT;i++){const c=all5[i],sh=dir==='LONG'?c.low<=sl:c.high>=sl,th=dir==='LONG'?c.high>=tp:c.low<=tp;if(sh&&th)return{filled:true,fill:all5[fi].start,loss:true,win:false,exit:c.start,exit_reason:'AMBIGUOUS_SL_FIRST',r:-1,hold_days:(c.start-all5[fi].start)/DAY};if(th)return{filled:true,fill:all5[fi].start,loss:false,win:true,exit:c.start,exit_reason:'TARGET',r:Math.abs(tp-e)/s.risk,hold_days:(c.start-all5[fi].start)/DAY};if(sh)return{filled:true,fill:all5[fi].start,loss:true,win:false,exit:c.start,exit_reason:'SL',r:-1,hold_days:(c.start-all5[fi].start)/DAY}}const endC=all5.find(c=>c.start>=maxT)||all5.at(-1),r=(dir==='LONG'?(endC.close-e):(e-endC.close))/s.risk;return{filled:true,fill:all5[fi].start,loss:r<0,win:r>0,exit:endC.start,exit_reason:'TIME_14D',r,hold_days:(endC.start-all5[fi].start)/DAY}}
function dedupe(trades){const out=[];for(const s of trades.slice().sort((a,b)=>(a.signal||a.fill)-(b.signal||b.fill))){const k=`${s.type}:${s.direction}:${Number(s.entry).toFixed(6)}:${Number(s.sl).toFixed(6)}:${s.signal}`;if(!out.some(x=>x._k===k))out.push({...s,_k:k})}for(const x of out)delete x._k;return out}
function stats(trades,name){const x=trades.filter(t=>t.filled&&Number.isFinite(t.r)),w=x.filter(t=>t.r>0).length,l=x.filter(t=>t.r<=0).length;let eq=INITIAL,peak=eq,mdd=0,maxLs=0,ls=0;for(const t of x.slice().sort((a,b)=>a.fill-b.fill)){eq+=eq*RISK*t.r;peak=Math.max(peak,eq);mdd=Math.max(mdd,(peak-eq)/peak);if(t.r<=0){ls++;maxLs=Math.max(maxLs,ls)}else ls=0}return{name,trades:x.length,wins:w,losses:l,win_rate:x.length?w/x.length:null,avg_r:x.length?avg(x.map(t=>t.r)):null,expectancy_r:x.length?avg(x.map(t=>t.r)):null,avg_hold_days:x.length?avg(x.map(t=>t.hold_days||0)):null,max_consecutive_losses:maxLs,final_equity:eq,return_pct:(eq/INITIAL-1)*100,max_drawdown_pct:mdd*100}}

const all5=parse(),m15=agg(all5,15),h1=agg(all5,60),h4=agg(all5,240),d1=agg(all5,1440);
const idx5=new Map(all5.map((c,i)=>[c.start,i]));
const daySignals=[],dayConsumed=new Set(),dayCycles=new Set();
for(const c of all5.filter(x=>x.start>=START&&x.start<=END)){
  const t=c.start+300000,h5=closed(all5,t,300000).slice(-120),a15=closed(m15,t,900000).slice(-100),a60=closed(h1,t,H).slice(-120),a240=closed(h4,t,4*H).slice(-100),D=closed(d1,t,DAY).slice(-30);
  const pois=dayPois({a15,a60,a240,D,all5,t});
  for(const p of pois){const dir=p.direction,pid=`${dir}:${p.poi_source}:${p.poi_created_at}:${p.poi_low.toFixed(4)}:${p.poi_high.toFixed(4)}`;if(dayConsumed.has(pid))continue;const ev=evaluateEntryTrigger({candles5m:h5,item:p});if(!ev.ready||!ev.trigger)continue;const tr=ev.trigger;if(tr.retrace_start!==h5.at(-1)?.start||dayCycles.has(tr.cycle_id))continue;if(dir==='LONG'?tr.structural_sl>=tr.entry_mid:tr.structural_sl<=tr.entry_mid)continue;const o=dayOutcome(tr,all5,idx5.get(c.start));if(!o.filled)continue;dayCycles.add(tr.cycle_id);dayConsumed.add(pid);const r=o.hit2?3:o.loss?-1:o.hit1?2:0;daySignals.push({type:'DAY',signal:c.start,direction:dir,poi_tf:p.poi_tf,poi_source:p.poi_source,entry:tr.entry_mid,sl:tr.structural_sl,live_rr:tr.live_rr,r,hold_days:o.exit?(o.exit-o.fill)/DAY:0,...o})}
}
const dayUnique=dedupe(daySignals);

const swingSignals=[],used=new Set();
for(const c of h1.filter(x=>x.start>=START&&x.start<=END)){const t=c.start+H,H4=closed(h4,t,4*H).slice(-120),D=closed(d1,t,DAY).slice(-120),H1=closed(h1,t,H).slice(-200);for(const dir of ['LONG','SHORT'])for(const [src,tf] of [[D,'1D'],[H4,'4H']]){const p=activeFvg(src,dir,tf);if(!p)continue;const pid=`${dir}:${tf}:${p.poi_created_at}:${p.poi_low}:${p.poi_high}`;if(used.has(pid))continue;const s=swingSetup(H4,H1,dir,p);if(!s||s.signal!==H1.at(-1)?.start)continue;const target=swingTarget(s,H4,D);if(!target)continue;const rr=Math.abs(target.price-s.entry)/s.risk;if(rr<1.5)continue;const startIdx=idx5.get(s.signal);if(startIdx==null)continue;const o=swingOutcome(s,all5,startIdx,target);used.add(pid);if(o.filled)swingSignals.push({type:'SWING',...s,target:target.price,target_tf:target.tf,target_rr:rr,...o})}}
const swingUnique=dedupe(swingSignals);
const dayStats=stats(dayUnique,'DAY'),swingStats=stats(swingUnique,'SWING');const combined=[...dayUnique,...swingUnique].filter(x=>x.filled&&Number.isFinite(x.r)).sort((a,b)=>a.fill-b.fill);const combinedStats=stats(combined,'COMBINED');
const byMonth={};for(const t of combined){const m=new Date(t.fill).toISOString().slice(0,7);byMonth[m]??={DAY:0,SWING:0};byMonth[m][t.type]++}
const bySource={};for(const t of dayUnique){const k=t.poi_source||t.poi_tf;bySource[k]??={trades:0,wins:0,losses:0,sum_r:0};bySource[k].trades++;if(t.r>0)bySource[k].wins++;else bySource[k].losses++;bySource[k].sum_r+=t.r}for(const v of Object.values(bySource)){v.win_rate=v.trades?v.wins/v.trades:null;v.avg_r=v.trades?v.sum_r/v.trades:null;delete v.sum_r}
console.log('BACKTEST_RESULT_START');
console.log(JSON.stringify({symbol:SYMBOL,data_source:'Binance Vision USD-M futures proxy',period:{start:new Date(START).toISOString(),end:new Date(END).toISOString()},initial_equity:INITIAL,risk_per_trade_pct:RISK,definitions:{DAY:'Expanded intraday POIs: 15m/1H FVG + PDH/PDL + Asia high/low + 1H/4H swing liquidity -> same strict 5m sweep/MSS/displacement/FVG, max entry wait 30m',SWING:'1D/4H POI -> 4H liquidity sweep -> 1H MSS/displacement/FVG -> 4H structural SL -> nearest HTF liquidity target, max hold 14d'},summary:{DAY:dayStats,SWING:swingStats,COMBINED:combinedStats},by_month:byMonth,day_by_source:bySource,day_trades:dayUnique,swing_trades:swingUnique},null,2));
console.log('BACKTEST_RESULT_END');
