const BYBIT_BASE="https://api.bybit.com",SCAN_CSV="https://raw.githubusercontent.com/feelmebaby79-a11y/bybit-trading-screener/main/latest/scan_results.csv",STATE_TTL_SECONDS=172800;
function cacheRequest(k){return new Request(`https://oi-alert-state.invalid/${encodeURIComponent(k)}`)}async function stateHas(e,k){if(e.ENTRY_DEDUPE?.get)return(await e.ENTRY_DEDUPE.get(k))!==null;try{return!!(await caches.default.match(cacheRequest(k)))}catch{return false}}async function statePut(e,k){if(e.ENTRY_DEDUPE?.put){await e.ENTRY_DEDUPE.put(k,"1",{expirationTtl:STATE_TTL_SECONDS});return}try{await caches.default.put(cacheRequest(k),new Response("1",{headers:{"cache-control":`max-age=${STATE_TTL_SECONDS}`}}))}catch{}}
async function bybit(path,p){const u=new URL(BYBIT_BASE+path);Object.entries(p).forEach(([k,v])=>u.searchParams.set(k,String(v)));const r=await fetch(u);if(!r.ok)throw Error(`Bybit HTTP ${r.status}`);const d=await r.json();if(d.retCode!==0)throw Error(d.retMsg);return d.result||{}}
async function fetchUniverse(){const r=await fetch(SCAN_CSV);if(!r.ok)throw Error(`scan csv ${r.status}`);const a=(await r.text()).replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean),h=a[0].split(","),i=h.indexOf("symbol");return[...new Set(a.slice(1).map(x=>x.split(",")[i]?.trim().toUpperCase()).filter(x=>/^[A-Z0-9]{3,30}USDT$/.test(x)))]}
async function oiHistory(s){const x=(await bybit("/v5/market/open-interest",{category:"linear",symbol:s,intervalTime:"5min",limit:50})).list||[];return x.map(r=>({t:+r.timestamp,v:+r.openInterest})).filter(r=>Number.isFinite(r.v)).sort((a,b)=>a.t-b.t)}
async function snapGet(env,key){if(env.ENTRY_DEDUPE?.get){const v=await env.ENTRY_DEDUPE.get(key);return v?+v:null}return null}async function snapPut(env,key,v){if(env.ENTRY_DEDUPE?.put)await env.ENTRY_DEDUPE.put(key,String(v),{expirationTtl:3600})}
function pct(n,p){return Number.isFinite(n)&&Number.isFinite(p)&&p>0?(n/p-1)*100:null}function histChange(a,b){return a.length>b?pct(a.at(-1).v,a.at(-1-b).v):null}
async function oiMetrics(env,s,minute){const h=await oiHistory(s),cur=h.at(-1)?.v,prev1=await snapGet(env,`oi-snap:${s}:${minute-1}`),prev5=await snapGet(env,`oi-snap:${s}:${minute-5}`);if(Number.isFinite(cur))await snapPut(env,`oi-snap:${s}:${minute}`,cur);return{oi1:pct(cur,prev1),oi5:Number.isFinite(prev5)?pct(cur,prev5):histChange(h,1),oi15:histChange(h,3),oi1h:histChange(h,12),oi4h:histChange(h,48)}}
async function prices(s){const q=async(i,l,b)=>{const x=(await bybit("/v5/market/kline",{category:"linear",symbol:s,interval:i,limit:l})).list||[],a=x.map(r=>({t:+r[0],c:+r[4]})).sort((x,y)=>x.t-y.t);return a.length>b?pct(a.at(-1).c,a.at(-1-b).c):null};return{price1m:await q("1",3,1),price5m:await q("5",3,1),price1h:await q("15",6,4)}}
function classify(x){const persistent=[x.oi5,x.oi15,x.oi1h,x.oi4h].filter(Number.isFinite).every(v=>v>0),acceleration=Number.isFinite(x.oi1)&&Number.isFinite(x.oi5)?x.oi1*5>x.oi5*1.2:x.oi15>0&&x.oi1h>0&&x.oi15*4>x.oi1h*1.2;const surge=(x.oi1??-99)>=1.5||(x.oi5??-99)>=3||(x.oi15??-99)>=5||(x.oi1h??-99)>=10||(x.oi4h??-99)>=20,early=acceleration&&((x.oi1??-99)>=0.5||(x.oi5??-99)>=1.5||(x.oi15??-99)>=3);return{hit:surge||early,level:surge?"SURGE":early?"ACCELERATION":null,persistent,acceleration}}
async function sendTelegram(e,m){const t=String(e.TELEGRAM_BOT_TOKEN||"").trim(),c=String(e.TELEGRAM_CHAT_ID||"").trim();if(!t||!c)throw Error("Telegram env missing");const r=await fetch(`https://api.telegram.org/bot${t}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:c,text:m,parse_mode:"HTML"})});if(!r.ok)throw Error(`Telegram ${r.status}`)}function f(v){return Number.isFinite(v)?`${v>=0?"+":""}${v.toFixed(2)}%`:"n/a"}
function message(x){const surge=x.level==="SURGE";return`${surge?"🚨":"🔥"} <b>${surge?"OI 급등 감지":"OI 증가 가속 감지"}</b>\n<b>${x.symbol}</b>\nOI 1m: <b>${f(x.oi1)}</b>\nOI 5m: <b>${f(x.oi5)}</b>\nOI 15m: <b>${f(x.oi15)}</b>\nOI 1H: <b>${f(x.oi1h)}</b>\nOI 4H: <b>${f(x.oi4h)}</b>\nPrice 1m: <b>${f(x.price1m)}</b>\nPrice 5m: <b>${f(x.price5m)}</b>\nPrice 1H: <b>${f(x.price1h)}</b>\n지속 증가: <b>${x.persistent?"YES":"NO"}</b> / 가속: <b>${x.acceleration?"YES":"NO"}</b>\n\n<b>OI 알림은 ENTRY 신호가 아닙니다.</b>`}
export async function runScheduledOiSurgeWatch(env,scheduledTime=Date.now()){const w=new Date(+scheduledTime||Date.now()),absoluteMinute=Math.floor(w.getTime()/60000),symbols=await fetchUniverse(),hits=[],sent=[],errors=[];for(const symbol of symbols)try{const om=await oiMetrics(env,symbol,absoluteMinute),c=classify(om);if(!c.hit)continue;const x={symbol,...om,...await prices(symbol),...c};hits.push(x);const key=`oi-alert:${symbol}:${c.level}:${w.toISOString().slice(0,13)}`;if(await stateHas(env,key))continue;await sendTelegram(env,message(x));await statePut(env,key);sent.push(x)}catch(e){errors.push({symbol,error:e?.message||String(e)})}return{ok:true,generated_at:new Date().toISOString(),checked_symbols:symbols.length,hits,telegram_sent:sent,errors}}
