import baseWorker from "./worker.js";
import { evaluateEntryTrigger } from "./entry_trigger.js";

const BYBIT_BASE="https://api.bybit.com";
const GITHUB_OWNER="feelmebaby79-a11y",GITHUB_REPO="bybit-trading-screener",GITHUB_BRANCH="main";
const STATE_TTL_SECONDS=60*60*24*7;
const POSITION_ONLY_MODE=false;
const POSITION_ONLY_SYMBOLS=new Set(["VANAUSDT","MSTRUSDT","ASTERUSDT"]);
const stateMemory=new Map();

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=UTF-8","cache-control":"no-store","access-control-allow-origin":"*"}});}
function isAuthorizedWorkerRequest(request,env){const k=String(env.WORKER_ACCESS_KEY||"").trim(),a=request.headers.get("Authorization")||"";return!!k&&a.startsWith("Bearer ")&&a.slice(7).trim()===k;}
async function fetchWatchlist(){const url=`https://raw.githubusercontent.com/${GITHUB_OWNER}/${GITHUB_REPO}/${GITHUB_BRANCH}/latest/watchlist.json?ts=${Date.now()}`;const r=await fetch(url,{cache:"no-store",headers:{accept:"application/json","cache-control":"no-cache","user-agent":"bybit-realtime-poi-watcher"}});if(!r.ok)throw new Error(`GitHub watchlist HTTP ${r.status}`);return r.json();}
function symbolAllowed(symbol){return !POSITION_ONLY_MODE||POSITION_ONLY_SYMBOLS.has(String(symbol||"").toUpperCase());}
async function fetchTicker(symbol){const u=new URL(BYBIT_BASE+"/v5/market/tickers");u.searchParams.set("category","linear");u.searchParams.set("symbol",symbol);const r=await fetch(u,{headers:{accept:"application/json"}});if(!r.ok)throw new Error(`Bybit ticker HTTP ${r.status}`);const d=await r.json();if(d.retCode!==0)throw new Error(`Bybit ticker ${d.retCode}: ${d.retMsg}`);const p=Number(d.result?.list?.[0]?.lastPrice);if(!Number.isFinite(p))throw new Error(`Invalid ticker for ${symbol}`);return p;}
async function fetchCandles(symbol,interval,limit=120){const u=new URL(BYBIT_BASE+"/v5/market/kline");u.searchParams.set("category","linear");u.searchParams.set("symbol",symbol);u.searchParams.set("interval",String(interval));u.searchParams.set("limit",String(limit));const r=await fetch(u,{headers:{accept:"application/json"}});if(!r.ok)throw new Error(`Bybit kline HTTP ${r.status}`);const d=await r.json();if(d.retCode!==0)throw new Error(`Bybit kline ${d.retCode}: ${d.retMsg}`);return(Array.isArray(d.result?.list)?d.result.list:[]).map(x=>({start:Number(x[0]),open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4])}));}
async function fetchRecentMinuteCandles(symbol){return fetchCandles(symbol,"1",4);}
function closedOldestFirst(newestFirst){return newestFirst.slice(1).reverse();}
function inRange(v,l,h){return v>=Math.min(l,h)&&v<=Math.max(l,h);}
function touches(c,l,h){return!!c&&Number.isFinite(c.low)&&Number.isFinite(c.high)&&c.high>=Math.min(l,h)&&c.low<=Math.max(l,h);}
function nullableNumber(v){if(v===null||v===undefined||v==="")return null;const x=Number(v);return Number.isFinite(x)?x:null;}
function normalizeItem(x){return{symbol:String(x?.symbol||"").trim().toUpperCase(),direction:String(x?.direction||"").trim().toUpperCase(),score:nullableNumber(x?.score),poi_low:nullableNumber(x?.poi_low),poi_high:nullableNumber(x?.poi_high),status:String(x?.status||"").trim().toUpperCase(),trigger_model:x?.trigger_model||null,updated_at:x?.updated_at||null,minimum_rr:nullableNumber(x?.minimum_rr)};}
function formatPrice(v){if(!Number.isFinite(v))return"n/a";if(v>=1000)return v.toFixed(2);if(v>=1)return v.toFixed(4);if(v>=.01)return v.toFixed(5);return v.toFixed(8);}
function priceKey(v){return Number(v).toPrecision(12);}
function poiKey(p){return `${p.symbol}:${p.direction}:${p.poi_tf||"MANUAL"}:${priceKey(p.poi_low)}:${priceKey(p.poi_high)}:${p.poi_created_at||"manual"}`;}
function cacheRequest(key){return new Request(`https://state.bybit-trading-screener.invalid/${encodeURIComponent(key)}`);}
function pruneState(now=Date.now()){for(const[k,v]of stateMemory.entries())if(now-v.at>STATE_TTL_SECONDS*1000)stateMemory.delete(k);}
async function stateGetValue(env,key){if(!key)return null;if(env.ENTRY_DEDUPE?.get){const v=await env.ENTRY_DEDUPE.get(key);return v===null?null:String(v);}pruneState();if(stateMemory.has(key))return stateMemory.get(key).value;try{const r=await caches.default.match(cacheRequest(key));return r?await r.text():null;}catch{return null;}}
async function stateHas(env,key){return(await stateGetValue(env,key))!==null;}
async function statePutValue(env,key,value="1"){if(!key)return;const v=String(value);if(env.ENTRY_DEDUPE?.put){await env.ENTRY_DEDUPE.put(key,v,{expirationTtl:STATE_TTL_SECONDS});return;}stateMemory.set(key,{value:v,at:Date.now()});try{await caches.default.put(cacheRequest(key),new Response(v,{headers:{"cache-control":`max-age=${STATE_TTL_SECONDS}`}}));}catch{}}
async function statePut(env,key){return statePutValue(env,key,"1");}

function candleRange(c){return Math.max(c.high-c.low,1e-12);}
function candleBody(c){return Math.abs(c.close-c.open);}
function htfDisplacement(cs,i,direction){if(i<5||i>=cs.length)return false;const c=cs[i],prior=cs.slice(i-5,i),avgRange=prior.reduce((a,x)=>a+candleRange(x),0)/prior.length,avgBody=prior.reduce((a,x)=>a+candleBody(x),0)/prior.length,r=candleRange(c),directional=direction==="LONG"?c.close>c.open:c.close<c.open,closeLocation=direction==="LONG"?(c.close-c.low)/r:(c.high-c.close)/r;return directional&&r>=Math.max(avgRange*1.25,1e-12)&&candleBody(c)>=Math.max(avgBody*1.35,r*0.5)&&closeLocation>=0.65;}
function latestDirectionalFvg(candles,direction,tf){const cs=closedOldestFirst(candles);for(let i=cs.length-1;i>=2;i--){const a=cs[i-2],c=cs[i];let low=null,high=null,kind=null;if(direction==="LONG"&&c.low>a.high){low=a.high;high=c.low;kind="BULL_FVG";}if(direction==="SHORT"&&c.high<a.low){low=c.high;high=a.low;kind="BEAR_FVG";}if(low===null)continue;if(!htfDisplacement(cs,i-1,direction))continue;const later=cs.slice(i+1),invalid=later.some(x=>direction==="LONG"?x.close<low:x.close>high);if(invalid)continue;return{poi_low:low,poi_high:high,poi_tf:tf,poi_source:kind,poi_created_at:c.start};}return null;}
function manualPoi(item){if(item.poi_low===null||item.poi_high===null)return null;return{...item,poi_tf:"1H/15m",poi_source:"MANUAL_VALIDATED",poi_created_at:"manual"};}
async function resolvePois(item){if(item.status!=="ACTIVE"||!symbolAllowed(item.symbol))return[];const [c15,c60]=await Promise.all([fetchCandles(item.symbol,"15",100),fetchCandles(item.symbol,"60",100)]);const candidates=[manualPoi(item),latestDirectionalFvg(c15,item.direction,"15m"),latestDirectionalFvg(c60,item.direction,"1H")].filter(Boolean).map(p=>({...item,...p}));const seen=new Set(),out=[];for(const p of candidates){const k=`${priceKey(p.poi_low)}:${priceKey(p.poi_high)}`;if(seen.has(k))continue;seen.add(k);out.push({...p,poi_id:poiKey(p)});}return out;}

async function sendTelegram(env,message){const token=String(env.TELEGRAM_BOT_TOKEN||"").trim(),chatId=String(env.TELEGRAM_CHAT_ID||"").trim();if(!token||!chatId)throw new Error("TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID is missing");const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text:message,parse_mode:"HTML",disable_web_page_preview:true})});const d=await r.json();if(!r.ok||d.ok!==true)throw new Error(`Telegram send failed: ${r.status} ${JSON.stringify(d).slice(0,300)}`);return d;}
function buildPoiMessage(i,test=false,label="TEST MODE"){const prefix=test?`🧪 <b>${label}</b>\n`:"🚨 <b>POI 도착 알림</b>\n";return`${prefix}<b>${i.symbol} ${i.direction}</b> / ${i.score??"-"}점\nPOI TF: <b>${i.poi_tf||"1H / 15m"}</b>\nPOI Source: <b>${i.poi_source||"validated"}</b>\nEntry TF: <b>5m</b>\n현재가: <code>${formatPrice(i.last)}</code>\nPOI: <code>${formatPrice(i.poi_low)} ~ ${formatPrice(i.poi_high)}</code>`;}
function buildEntryMessage(item,t,test=false){const z=t.entry_zone||[],prefix=test?"🧪 <b>ENTRY TEST MODE</b>\n":"🎯 <b>ENTRY CANDIDATE</b>\n";return`${prefix}<b>${item.symbol} ${item.direction}</b>\nEntry zone: <code>${formatPrice(z[0])} ~ ${formatPrice(z[1])}</code>\nEntry mid: <code>${formatPrice(t.entry_mid)}</code>\nStructural SL: <code>${formatPrice(t.structural_sl)}</code>\nTP1: <code>${formatPrice(t.tp1)}</code> / R:R <b>${Number(t.rr_tp1).toFixed(2)}:1</b>\nTP2: <code>${formatPrice(t.tp2)}</code> / R:R <b>${Number(t.rr_tp2).toFixed(2)}:1</b>`;}

async function evaluateRealtimeWatchlist(env){const p=await fetchWatchlist(),items=(Array.isArray(p?.items)?p.items:[]).map(normalizeItem).filter(x=>symbolAllowed(x.symbol)),results=[];for(const item of items){if(item.status!=="ACTIVE"){results.push({...item,monitoring:false});continue;}try{const [last,c1,pois]=await Promise.all([fetchTicker(item.symbol),fetchRecentMinuteCandles(item.symbol),resolvePois(item)]);const forming=c1[0]||null,closed1=c1[1]||null,prevClosed1=c1[2]||null;for(const poi of pois){const consumed=await stateHas(env,`consumed:${poi.poi_id}`),inPoi=inRange(last,poi.poi_low,poi.poi_high),formingTouch=touches(forming,poi.poi_low,poi.poi_high),closedTouch=touches(closed1,poi.poi_low,poi.poi_high),prevClosedTouch=touches(prevClosed1,poi.poi_low,poi.poi_high),touchDetected=!consumed&&(inPoi||formingTouch||closedTouch);results.push({...poi,monitoring:!consumed,consumed,last,in_poi:inPoi,touch_detected:touchDetected,first_arrival:touchDetected&&!prevClosedTouch,arrival_basis:"ticker_or_1m_range_overlap",arrival_candle_start:formingTouch?forming?.start:closedTouch?closed1?.start:null,checked_at:new Date().toISOString()});}}catch(e){results.push({...item,monitoring:true,error:e?.message||String(e)});}}return{ok:true,generated_at:new Date().toISOString(),position_only_mode:POSITION_ONLY_MODE,allowed_symbols:[...POSITION_ONLY_SYMBOLS],watchlist_updated_at:p?.updated_at||null,arrivals:results.filter(x=>x.touch_detected===true),items:results};}

async function evaluateEntryWatchlist(env){const p=await fetchWatchlist(),items=(Array.isArray(p?.items)?p.items:[]).map(normalizeItem).filter(x=>symbolAllowed(x.symbol)),results=[];for(const item of items){if(item.status!=="ACTIVE"){results.push({...item,entry_monitoring:false});continue;}try{const [c5,pois]=await Promise.all([fetchCandles(item.symbol,"5",120),resolvePois(item)]),m5=closedOldestFirst(c5),latest5=m5.at(-1)?.start||null;for(const poi of pois){const consumed=await stateHas(env,`consumed:${poi.poi_id}`);if(consumed){results.push({...poi,entry_monitoring:false,consumed:true,latest_closed_5m:latest5});continue;}const touchRaw=await stateGetValue(env,`poi-touch-ts:${poi.poi_id}`),touchTs=Number(touchRaw);if(!Number.isFinite(touchTs)||touchTs<=0){results.push({...poi,entry_monitoring:true,consumed:false,entry_ready:false,fresh_entry_candidate:false,entry_stage:"5m:WAIT_POI_TOUCH",poi_touch_start:null,latest_closed_5m:latest5,checked_at:new Date().toISOString()});continue;}const e=evaluateEntryTrigger({candles5m:m5,item:{...poi,poi_touch_start:touchTs}}),t=e.trigger||null,fresh=!!(e.ready&&t&&t.tf==="5m"&&t.retrace_start===latest5);results.push({...poi,poi_touch_start:touchTs,entry_monitoring:true,consumed:false,entry_ready:e.ready,fresh_entry_candidate:fresh,entry_stage:e.stage,trigger:t,latest_closed_5m:latest5,checked_at:new Date().toISOString()});}}catch(err){results.push({...item,entry_monitoring:true,error:err?.message||String(err)});}}return{ok:true,generated_at:new Date().toISOString(),position_only_mode:POSITION_ONLY_MODE,allowed_symbols:[...POSITION_ONLY_SYMBOLS],watchlist_updated_at:p?.updated_at||null,candidates:results.filter(x=>x.fresh_entry_candidate===true),items:results};}

async function runSyntheticPoiTest(env,symbol,label="TEST MODE"){const last=await fetchTicker(symbol),w=Math.max(Math.abs(last)*.0005,1e-12),i={symbol,direction:"TEST",score:100,poi_low:last-w,poi_high:last+w,last,poi_tf:"1H/15m",poi_source:"SYNTHETIC"};await sendTelegram(env,buildPoiMessage(i,true,label));return{ok:true,test:true,symbol,last,synthetic_poi:[i.poi_low,i.poi_high],telegram_sent:true};}
async function runSyntheticEntryTest(env,symbol){const last=await fetchTicker(symbol),risk=Math.max(Math.abs(last)*.002,1e-12),item={symbol,direction:"LONG",score:100,poi_tf:"1H/15m"},t={tf:"5m",entry_zone:[last-risk*.25,last+risk*.25],entry_mid:last,structural_sl:last-risk,tp1:last+2*risk,tp2:last+2.5*risk,rr_tp1:2,rr_tp2:2.5,event_id:`TEST:${symbol}:${Date.now()}`};await sendTelegram(env,buildEntryMessage(item,t,true));return{ok:true,test:true,type:"entry",symbol,telegram_sent:true,event_id:t.event_id};}

export default{async fetch(request,env,ctx){const u=new URL(request.url);if(request.method==="GET"&&u.pathname==="/realtime-watch"){try{return json(await evaluateRealtimeWatchlist(env));}catch(e){return json({ok:false,error:e?.message||String(e)},500);}}if(request.method==="GET"&&u.pathname==="/entry-watch"){try{return json(await evaluateEntryWatchlist(env));}catch(e){return json({ok:false,error:e?.message||String(e)},500);}}if(request.method==="POST"&&u.pathname==="/test-poi-telegram"){if(!isAuthorizedWorkerRequest(request,env))return json({ok:false,error:"Unauthorized"},401);const s=String(u.searchParams.get("symbol")||"BTCUSDT").trim().toUpperCase();try{return json(await runSyntheticPoiTest(env,s));}catch(e){return json({ok:false,error:e?.message||String(e)},500);}}if(request.method==="POST"&&u.pathname==="/test-entry-telegram"){if(!isAuthorizedWorkerRequest(request,env))return json({ok:false,error:"Unauthorized"},401);const s=String(u.searchParams.get("symbol")||"BTCUSDT").trim().toUpperCase();try{return json(await runSyntheticEntryTest(env,s));}catch(e){return json({ok:false,error:e?.message||String(e)},500);}}return baseWorker.fetch(request,env,ctx);}};
