import realtimeWorker from "./worker_realtime.js";
import { runScheduledOiSurgeWatch } from "./oi_surge_alert.js";

const GITHUB_OWNER="feelmebaby79-a11y",GITHUB_REPO="bybit-trading-screener",GITHUB_BRANCH="main";
const STATE_TTL_SECONDS=60*60*24*7;

function formatPrice(v){const n=Number(v);if(!Number.isFinite(n))return"n/a";if(n>=1000)return n.toFixed(2);if(n>=1)return n.toFixed(4);if(n>=.01)return n.toFixed(5);return n.toFixed(8)}
function cacheRequest(key){return new Request(`https://state.bybit-trading-screener.invalid/${encodeURIComponent(key)}`)}
async function stateHas(env,key){if(!key)return false;if(env.ENTRY_DEDUPE?.get)return(await env.ENTRY_DEDUPE.get(key))!==null;try{return!!(await caches.default.match(cacheRequest(key)))}catch{return false}}
async function statePut(env,key){if(!key)return;if(env.ENTRY_DEDUPE?.put){await env.ENTRY_DEDUPE.put(key,"1",{expirationTtl:STATE_TTL_SECONDS});return}try{await caches.default.put(cacheRequest(key),new Response("1",{headers:{"cache-control":`max-age=${STATE_TTL_SECONDS}`}}))}catch{}}
async function sendTelegram(env,message){const token=String(env.TELEGRAM_BOT_TOKEN||"").trim(),chatId=String(env.TELEGRAM_CHAT_ID||"").trim();if(!token||!chatId)throw new Error("TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID is missing");const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:chatId,text:message,parse_mode:"HTML",disable_web_page_preview:true})});const d=await r.json();if(!r.ok||d.ok!==true)throw new Error(`Telegram send failed: ${r.status} ${JSON.stringify(d).slice(0,300)}`);return d}
async function fetchCurrentWatchlist(){const url=`https://raw.githubusercontent.com/${GITHUB_OWNER}/${GITHUB_REPO}/${GITHUB_BRANCH}/latest/watchlist.json?ts=${Date.now()}`;const r=await fetch(url,{cache:"no-store",headers:{accept:"application/json","cache-control":"no-cache","user-agent":"bybit-safe-alert-wrapper"}});if(!r.ok)throw new Error(`GitHub watchlist HTTP ${r.status}`);return r.json()}
function activeSymbols(w){return new Set((Array.isArray(w?.items)?w.items:[]).filter(x=>String(x?.status||"").toUpperCase()==="ACTIVE").map(x=>String(x?.symbol||"").trim().toUpperCase()).filter(Boolean))}
function validPoi(i){const low=Number(i?.poi_low),high=Number(i?.poi_high),tf=String(i?.poi_tf||""),source=String(i?.poi_source||"");return !i?.error&&Number.isFinite(low)&&Number.isFinite(high)&&low>0&&high>0&&!!i?.poi_id&&["1H","15m","1H/15m"].includes(tf)&&!!source&&source!=="undefined"}
function buildNewPoiMessage(i){return`🆕 <b>새 POI 감지</b>\n<b>${i.symbol} ${i.direction}</b> / ${i.score??"-"}점\nPOI TF: <b>${i.poi_tf}</b>\nPOI Source: <b>${i.poi_source}</b>\nPOI: <code>${formatPrice(i.poi_low)} ~ ${formatPrice(i.poi_high)}</code>\n\n기본 감시종목/오늘 추천종목에서 새 POI가 확인되었습니다.\nEntry TF: <b>5m only</b>`}
function buildPoiArrivalMessage(i){return`🚨 <b>POI 도착 알림</b>\n<b>${i.symbol} ${i.direction}</b> / ${i.score??"-"}점\nPOI TF: <b>${i.poi_tf}</b>\nPOI Source: <b>${i.poi_source}</b>\nEntry TF: <b>5m</b>\n현재가: <code>${formatPrice(i.last)}</code>\nPOI: <code>${formatPrice(i.poi_low)} ~ ${formatPrice(i.poi_high)}</code>\n\n<b>POI 도착은 진입 신호가 아닙니다.</b>\n다음 확인: ${i.trigger_model||"liquidity sweep → MSS/CHoCH + displacement → FVG/validated OB retracement"}\n<b>No retrace = no trade.</b>`}
function buildEntryMessage(i){const t=i.trigger||{},z=Array.isArray(t.entry_zone)?t.entry_zone:[],kind=t.zone?.kind||"FVG/OB",rr1=Number.isFinite(Number(t.rr_tp1))?Number(t.rr_tp1).toFixed(2):"n/a",rr2=Number.isFinite(Number(t.rr_tp2))?Number(t.rr_tp2).toFixed(2):"n/a";return`🎯 <b>ENTRY CANDIDATE</b>\n<b>${i.symbol} ${i.direction}</b> / ${i.score??"-"}점\nPOI TF: <b>${i.poi_tf}</b>\nEntry TF: <b>5m</b>\nTrigger: sweep → MSS/CHoCH + displacement → ${kind} retracement\nEntry zone: <code>${formatPrice(z[0])} ~ ${formatPrice(z[1])}</code>\nEntry mid: <code>${formatPrice(t.entry_mid)}</code>\nStructural SL: <code>${formatPrice(t.structural_sl)}</code>\nTP1: <code>${formatPrice(t.tp1)}</code> / R:R <b>${rr1}:1</b>\nTP2: <code>${formatPrice(t.tp2)}</code> / R:R <b>${rr2}:1</b>\n\n<b>진입 후보입니다. 시장가 추격 금지. No retrace = no trade.</b>`}
async function callRealtimeEndpoint(path,env,ctx){const response=await realtimeWorker.fetch(new Request(`https://internal${path}`),env,ctx),payload=await response.json();if(!response.ok||payload?.ok!==true)throw new Error(`${path} failed: ${response.status} ${JSON.stringify(payload).slice(0,300)}`);return payload}
async function getConsistentEvaluation(path,env,ctx){for(let attempt=1;attempt<=3;attempt++){const current=await fetchCurrentWatchlist(),evaluated=await callRealtimeEndpoint(path,env,ctx);if(String(evaluated.watchlist_updated_at||"")===String(current.updated_at||""))return{current,evaluated,attempt};console.log(JSON.stringify({event:"watchlist_race_retry",path,attempt,evaluated_watchlist_updated_at:evaluated.watchlist_updated_at,current_watchlist_updated_at:current.updated_at}))}throw new Error(`${path} could not obtain a consistent watchlist after 3 attempts`)}
async function runSafePoiWatch(env,ctx){const {current,evaluated,attempt}=await getConsistentEvaluation("/realtime-watch",env,ctx),active=activeSymbols(current),newPoiSent=[],arrivalSent=[],suppressed=[],errors=[];for(const i of Array.isArray(evaluated.items)?evaluated.items:[]){const symbol=String(i?.symbol||"").toUpperCase();if(!active.has(symbol)||!i?.monitoring||!validPoi(i)||i.poi_source==="MANUAL_VALIDATED"){if(i?.monitoring&&!validPoi(i))suppressed.push({symbol,reason:i?.error?"evaluation_error":"invalid_poi"});continue}const key=`announced:${i.poi_id}`;try{if(!(await stateHas(env,key))){await sendTelegram(env,buildNewPoiMessage(i));await statePut(env,key);newPoiSent.push({symbol,poi_id:i.poi_id})}}catch(e){errors.push({symbol,type:"new_poi",error:e?.message||String(e)})}}
for(const i of Array.isArray(evaluated.items)?evaluated.items:[]){const symbol=String(i?.symbol||"").toUpperCase();if(!active.has(symbol)||!i?.monitoring||!validPoi(i)||i?.in_poi!==true)continue;const arrivalKey=`poi-arrival:${i.poi_id}`;try{if(await stateHas(env,arrivalKey)){suppressed.push({symbol,reason:"duplicate_poi_arrival"});continue}await sendTelegram(env,buildPoiArrivalMessage(i));await statePut(env,arrivalKey);arrivalSent.push({symbol,poi_id:i.poi_id})}catch(e){errors.push({symbol,type:"arrival",error:e?.message||String(e)})}}
console.log(JSON.stringify({event:"safe_poi_cron",generated_at:evaluated.generated_at,watchlist_updated_at:current.updated_at,consistency_attempt:attempt,active_symbols:[...active],new_poi_sent:newPoiSent,arrivals_sent:arrivalSent,suppressed,errors}));return{ok:errors.length===0,new_poi_sent:newPoiSent,arrivals_sent:arrivalSent,suppressed,errors}}
async function runSafeEntryWatch(env,ctx){const {current,evaluated,attempt}=await getConsistentEvaluation("/entry-watch",env,ctx),active=activeSymbols(current),sent=[],suppressed=[],errors=[];for(const i of Array.isArray(evaluated.candidates)?evaluated.candidates:[]){const symbol=String(i?.symbol||"").toUpperCase(),eventId=i?.trigger?.event_id;if(!active.has(symbol)||!validPoi(i)||!i?.fresh_entry_candidate||!eventId){suppressed.push({symbol,reason:"invalid_or_stale_entry"});continue}const entryKey=`entry:${eventId}`,consumedKey=`consumed:${i.poi_id}`;try{if(await stateHas(env,consumedKey)){suppressed.push({symbol,reason:"poi_consumed"});continue}if(await stateHas(env,entryKey)){suppressed.push({symbol,reason:"duplicate_entry"});continue}await sendTelegram(env,buildEntryMessage(i));await statePut(env,entryKey);await statePut(env,consumedKey);sent.push({symbol,event_id:eventId,poi_id:i.poi_id})}catch(e){errors.push({symbol,type:"entry",error:e?.message||String(e)})}}
console.log(JSON.stringify({event:"safe_entry_cron",generated_at:evaluated.generated_at,watchlist_updated_at:current.updated_at,consistency_attempt:attempt,active_symbols:[...active],sent,suppressed,errors}));return{ok:errors.length===0,sent,suppressed,errors}}
function shouldRunEntryCron(controller){const scheduled=Number(controller?.scheduledTime),when=Number.isFinite(scheduled)?new Date(scheduled):new Date();return when.getUTCMinutes()%5===1}
export default{async fetch(request,env,ctx){return realtimeWorker.fetch(request,env,ctx)},async scheduled(controller,env,ctx){const jobs=[runSafePoiWatch(env,ctx).catch(e=>console.error("POI watch failed",e))];if(shouldRunEntryCron(controller))jobs.push(runSafeEntryWatch(env,ctx).catch(e=>console.error("Entry watch failed",e)));jobs.push(runScheduledOiSurgeWatch(env,controller?.scheduledTime).catch(e=>console.error("OI surge watch failed",e)));ctx.waitUntil(Promise.all(jobs))}};
